version: '3.4'
services:
  web:
    build:
        context: .
        cache_from:
            - mozmeao/kitsune:base-latest
            - kitsune:latest
        dockerfile: docker/dockerfiles/base
    image: kitsune:base-latest
    command: ./manage.py runserver 0.0.0.0:8000
    user: ${UID:-kitsune}
    depends_on:
      - mariadb
      - elasticsearch
      - redis
    ports:
      - "8000:8000"
  mariadb:
    image: mariadb:10.0
    environment:
      - MYSQL_ROOT_PASSWORD=kitsune
      - MYSQL_USER=kitsune
      - MYSQL_PASSWORD=kitsune
      - MYSQL_DATABASE=kitsune
    entrypoint:
      - docker-entrypoint.sh
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    volumes:
      - mysqlvolume:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:2.4

  redis:
    image: redis:3

volumes:
    mysqlvolume:
