version: "3.8"
services:
  web:
    build:
      context: .
      target: base
    command: ./bin/run-prod.sh
    env_file: .env
    volumes:
      - ./:/app:delegated
    user: ${UID:-kitsune}
    stdin_open: true
    tty: true
    depends_on:
      - mariadb
      - elasticsearch7
      - kibana
      - redis
      - celery
      - mailcatcher
    ports:
      - "8000:8000"

  mariadb:
    image: mariadb:10.7
    environment:
      - MYSQL_ROOT_PASSWORD=kitsune
      - MYSQL_USER=kitsune
      - MYSQL_PASSWORD=kitsune
      - MYSQL_DATABASE=kitsune
    entrypoint:
      - docker-entrypoint.sh
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
      - --sql-mode=ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    volumes:
      - mysqlvolume:/var/lib/mysql

  elasticsearch7:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./kitsune/search/dictionaries/synonyms:/usr/share/elasticsearch/config/synonyms

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch7:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch7:9200

  redis:
    image: redis:3

  celery:
    build:
      context: .
      target: base
    command: celery -A kitsune worker -l info -n default@%h
    env_file: .env
    volumes:
      - ./:/app:delegated
    user: ${UID:-kitsune}
    depends_on:
      - mariadb
      - redis

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"

volumes:
  mysqlvolume:
