services:
  web:
    build:
      context: .
      target: dev
    command: ./bin/run-prod.sh
    env_file: .env
    volumes:
      - ./:/app:delegated
      - /app/.venv
    user: ${UID:-kitsune}
    stdin_open: true
    tty: true
    depends_on:
      - postgres
      - elasticsearch
      - kibana
      - redis
      - celery
      - mailcatcher
    ports:
      - "8000:8000"

  node:
    image: node:22-bookworm
    working_dir: /app
    command: >
      sh -c "npm install && npm start"
    volumes:
      - ./:/app:delegated
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=development
    depends_on:
      - web

  beat:
    build:
      context: .
      target: dev
    command: ./bin/run-celery-beat.sh
    env_file: .env
    volumes:
      - ./:/app:delegated
      - /app/.venv
    user: ${UID:-kitsune}
    depends_on:
      - postgres
      - redis
    profiles:
      - beat

  celery:
    build:
      context: .
      target: dev
    command: bash -c "source /app/.venv/bin/activate && python -m celery -A kitsune worker -l info -n default@%h -Q celery,email"
    env_file: .env
    volumes:
      - ./:/app:delegated
      - /app/.venv
    user: ${UID:-1000}
    depends_on:
      - postgres
      - redis

  flower:
    build:
      context: .
      target: dev
    command: bash -c "source /app/.venv/bin/activate && python -m celery -A kitsune flower"
    env_file: .env
    volumes:
      - ./:/app:delegated
      - /app/.venv
    user: ${UID:-kitsune}
    depends_on:
      - redis
      - celery
    ports:
      - "5555:5555"
    profiles:
      - beat

  postgres:
    image: postgres:15.3
    shm_size: 1G
    environment:
      - POSTGRES_PASSWORD=kitsune
      - POSTGRES_USER=kitsune
      - POSTGRES_DB=kitsune
      - LC_ALL=C.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - pgvolume:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    environment:
      - discovery.type=single-node
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
      - xpack.security.enabled=false
      - action.destructive_requires_name=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./kitsune/search/dictionaries/synonyms:/usr/share/elasticsearch/config/synonyms

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

  redis:
    image: redis:3

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"

volumes:
  pgvolume:
  node_modules:
