version: '3.4'
services:
  web:
    image: mozmeao/kitsune:base-dev-${GIT_COMMIT_SHORT:-latest}
    command: ./bin/run-dev.sh
    env_file: .env
    volumes:
      - ./:/app:delegated
    user: ${UID:-kitsune}
    depends_on:
      - mariadb
      - elasticsearch
      - redis
    ports:
      - "8000:8000"

  test:
    image: mozmeao/kitsune:base-dev-${GIT_COMMIT_SHORT:-latest}
    command: ./bin/run-unit-tests.sh
    env_file: .env-test
    volumes:
      - ./:/app:delegated
    user: ${UID:-kitsune}
    depends_on:
      - mariadb
      - elasticsearch
      - redis

  test-js:
    image: mozmeao/kitsune:staticfiles-${GIT_COMMIT_SHORT:-latest}
    command: ./bin/run-mocha-tests.sh
    env_file: .env-test
    volumes:
      - ./:/app:delegated
    user: ${UID:-kitsune}

  test-image:
    image: mozmeao/kitsune:full-no-locales-${GIT_COMMIT_SHORT:-latest}
    command: ./bin/run-unit-tests.sh
    env_file: .env-test
    depends_on:
      - mariadb
      - elasticsearch
      - redis

  test-image-js:
    image: mozmeao/kitsune:staticfiles-${GIT_COMMIT_SHORT:-latest}
    command: ./bin/run-mocha-tests.sh
    env_file: .env-test

  # images
  base:
    build:
      context: .
      target: base
    image: mozmeao/kitsune:base-${GIT_COMMIT_SHORT:-latest}

  base-dev:
    build:
      context: .
      target: base-dev
    image: mozmeao/kitsune:base-dev-${GIT_COMMIT_SHORT:-latest}

  staticfiles:
    build:
      context: .
      target: staticfiles
    image: mozmeao/kitsune:staticfiles-${GIT_COMMIT_SHORT:-latest}

  locales:
    build:
      context: .
      target: locales
    image: mozmeao/kitsune:locales-${GIT_COMMIT_SHORT:-latest}

  full-no-locales:
    build:
      context: .
      target: full-no-locales
    image: mozmeao/kitsune:full-no-locales-${GIT_COMMIT_SHORT:-latest}

  full:
    build:
      context: .
      target: full
    image: mozmeao/kitsune:full-${GIT_COMMIT_SHORT:-latest}

  # EXTERNAL SERVICES
  mariadb:
    image: mariadb:10.0
    environment:
      - MYSQL_ROOT_PASSWORD=kitsune
      - MYSQL_USER=kitsune
      - MYSQL_PASSWORD=kitsune
      - MYSQL_DATABASE=kitsune
    entrypoint:
      - docker-entrypoint.sh
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    volumes:
      - mysqlvolume:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    environment:
      - discovery.type=single-node
      - http.cors.allow-origin="http://127.0.0.1:1358"
      - http.cors.enabled=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  redis:
    image: redis:3

volumes:
    mysqlvolume:
    esdata1:
