[tool.black]
line-length = 99
# NB: this can only be updated once black supports the target python version,
# so may lag behind the version of python we're using. This shouldn't matter
# unless we're using completely new syntax:
target-version = ['py38']
exclude = "^.*/migrations/.*$|kitsune/sumo/db_strings.py"

[tool.poetry]
name = "kitsune"
version = "0.1.0"
description = "Mozilla Support Platform"
authors = ["Your Name <you@example.com>"]
license = "BSD 3-Clause"

[tool.poetry.dependencies]
python = "^3.10"
APScheduler = "^3.8.1"
Django = "3.2.16"
babis = "^0.2.4"
Pillow = "^9.0.1"
bleach = "^4.1.0"
boto3 = "^1.20.26"
celery = "5.2.7"
dennis = "^1.1.0"
mozilla-django-oidc = "^2.0.0"
dj-database-url = "^0.5.0"
django-jinja = "^2.10.2"
lxml = "^4.9.1"
elasticsearch = "^7.16.2"
elasticsearch-dsl = "^7.4.0"
gunicorn = "^20.1.0"
gevent = "^21.12.0"
newrelic = "^7.2.4"
django-waffle = "^2.2.1"
python-decouple = "^3.5"
sentry-sdk = "^1.5.1"
whitenoise = "^5.3.0"
zenpy = "^2.0.24"
idna = "^3.3"
django-allow-cidr = "^0.3.1"
html5lib = "^1.1"
py-wikimarkup = "2.1.3"
python-dateutil = "^2.8.2"
python-memcached = "^1.59"
pytz = "^2021.3"
redis = "^4.1.0"
django-cors-headers = "^3.13.0"
django-enforce-host = "^1.0.1"
django-cache-url = "^3.2.3"
django-authority = {git = "https://github.com/jazzband/django-authority.git"}
django-extensions = "^3.1.5"
django-adminplus = "^0.5"
django-filter = "^21.1"
django-redis = "^5.2.0"
factory-boy = "^3.2.1"
Faker = "^11.1.0"
google-api-python-client = "^2.33.0"
timeout-decorator = "^0.5.0"
simplejson = "^3.17.6"
twython = "^3.9.1"
translate-toolkit = "^3.5.1"
django-ratelimit = "^3.0.1"
django-storages = "^1.12.3"
django-taggit = "^2.0.0"
django-user-agents = "^0.4.0"
django-watchman = "^1.2.0"
premailer = "^3.10.0"
pyquery = "^1.4.3"
parameterized = "^0.8.1"
Werkzeug = "^2.0.2"
commonware = "^0.6.0"
django-statici18n = "^2.2.0"
django-timezone-field = "^4.2.1"
djangorestframework = "^3.13.1"
django-activity-stream = "^0.10.0"
django-jsonfield-compat = "^0.4.4"
django-jsonfield-backport = "^1.0.4"
cffi = "^1.15.0"
django-mozilla-product-details = "^1.0.1"
PyMySQL = "^1.0.2"
django-csp = "^3.7"
oauthlib = "^3.2.1"
protobuf = "3.19.5"
Babel = "2.10.3"
Jinja2 = "^3.1.2"
google-auth = "^2.12.0"
pip = "22.2.2"
graphene-django = "~3.0.0"

[tool.poetry.dev-dependencies]
ipdb = "^0.13.9"
isort = "^5.10.1"
pep8 = "^1.7.1"
appnope = "^0.1.2"
argparse = "^1.4.0"
django-debug-toolbar = "^3.2.4"
django-cache-panel = "^0.1"
jsonschema = "^4.3.2"
pip = "^22.2.2"
pre-commit = "^2.16.0"
q = "^2.6"
rope = "^0.22.0"
pylint = "^2.12.2"
debugpy = "^1.5.1"
black = "^21.12b0"
flake8 = "^4.0.1"
urlwait = "^1.0"
testfixtures = "^6.18.3"
Sphinx = "^4.3.2"
recommonmark = "^0.7.1"
sphinx-rtd-theme = "^1.0.0"
sphinxcontrib-httpdomain = "^1.8.0"
tabulate = "^0.8.9"
pylint-django = "^2.5.3"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
