# Default config for Vagrant

# Don't change this; use vagrantconfig_local.yaml to override these
# settings instead.

memory: 256

# enable this to see verbose and debug puppet output
debug_mode: false

# set this to "gui" if vagrant cannot connect
boot_mode: none
