version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  lint:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Lint with pre-commit
          command: |
            pip install --upgrade pre-commit==2.15.0
            pre-commit run --all-files
  test-and-build:
    docker:
      - image: cimg/python:3.10
    environment:
      AWS_DEFAULT_REGION: us-west-2
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Build test image
          command: |
            cp .env-build .env
            ./bin/dc_ci.sh build --progress=plain test
      - run:
          # copy synonym files to elasticsearch7 container, since circleci doesn't support volume mounts:
          # https://circleci.com/docs/2.0/building-docker-images/#mounting-folders
          name: Copy synonym files to elasticsearch7
          command: |
            ./bin/dc_ci.sh up -d elasticsearch7
            docker cp ./kitsune/search/dictionaries/synonyms/. project_elasticsearch7_1:/usr/share/elasticsearch/config/synonyms
      - run:
          name: Run unit tests
          command: ./bin/dc_ci.sh run test ./bin/run-unit-tests.sh
      - run:
          name: Run js tests
          command: ./bin/dc_ci.sh run test npm run webpack:test
      - when:
          condition:
            or:
              - equal: [main, << pipeline.git.branch >>]
              - equal: [production, << pipeline.git.branch >>]
              - matches:
                  { pattern: "^prod-.+$", value: << pipeline.git.branch >> }
          steps:
            - run:
                name: Build prod image
                command: ./bin/dc_ci.sh build --progress=plain prod
            - run:
                name: Push prod image
                command: |
                  echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
                  source docker/bin/set_git_env_vars.sh
                  docker image tag mozilla/kitsune:prod-${GIT_COMMIT_SHORT} mozilla/kitsune:prod-latest
                  docker image push mozilla/kitsune:prod-${GIT_COMMIT_SHORT}
                  docker image push mozilla/kitsune:prod-latest
                  docker logout
            - aws-cli/setup
            - run:
                name: Upload staticfiles
                command: |
                  source docker/bin/set_git_env_vars.sh
                  ./docker/bin/upload-staticfiles.sh
            - run:
                name: Echo prod image hash
                command: |
                  source docker/bin/set_git_env_vars.sh
                  sed s/replaceme/${GIT_COMMIT_SHORT}/ .circleci/build.html > /tmp/build-status.html
                  echo -e 'build completed!\n'"hash: ${GIT_COMMIT_SHORT}\nimage: mozilla/kitsune:prod-${GIT_COMMIT_SHORT}"
            - store_artifacts:
                path: /tmp/build-status.html
                destination: build-status.html
workflows:
  version: 2
  lint-test-build:
    jobs:
      - lint
      - test-and-build
