# General settings
TARGET_ENVIRONMENT: stage
K8S_NAMESPACE: sumo-stage
SUMO_APP_NAME: sumo-stage
SUMO_SECRETS_NAME: sumo-secrets-stage
SUMO_WEB_DEPLOYMENT_NAME: sumo-stage-web
SUMO_CELERY_DEPLOYMENT_NAME: sumo-stage-celery
SUMO_CRON_DEPLOYMENT_NAME: sumo-stage-cron

# Env vars
SUMO_ENV_ALLOWED_HOSTS: "*"
SUMO_ENV_CELERY_ALWAYS_EAGER: False
SUMO_ENV_CSRF_COOKIE_SECURE: True
SUMO_ENV_DEBUG: False
SUMO_ENV_DOMAIN: localhost
SUMO_ENV_ENABLE_ADMIN: True
SUMO_ENV_ENABLE_WHITENOISE: True
SUMO_ENV_ENGAGE_ROBOTS: False
SUMO_ENV_ES_LIVE_INDEXING: True
SUMO_ENV_ES_USE_SSL: True
SUMO_ENV_HTTPS: True
SUMO_ENV_MEDIA_URL: https://stage-cdn.sumo.mozilla.net/
SUMO_ENV_PIPELINE_ENABLED: True
SUMO_ENV_PORT: 8000
SUMO_ENV_READ_ONLY: False
SUMO_ENV_SESSION_COOKIE_SECURE: True
SUMO_ENV_SITE_URL: http://stage.sumo.moz.works
SUMO_ENV_STAGE: False
SUMO_ENV_STATIC_URL: https://static-media-stage-cdn.sumo.mozilla.net/static/
SUMO_ENV_SECURE_HSTS_SECONDS: 0
SUMO_ENV_SECURE_BROWSER_XSS_FILTER: True
SUMO_ENV_SECURE_CONTENT_TYPE_NOSNIFF: True
SUMO_ENV_SECURE_SSL_REDIRECT: True

# Image settings
SUMO_IMAGE_PULL_POLICY: Always
SUMO_IMAGE_TAG: full-latest
SUMO_IMAGE: mozmeao/kitsune

# Requests/Limits
SUMO_MEMORY_LIMIT: 1Gi
SUMO_MEMORY_REQUEST: 256Mi
SUMO_CPU_LIMIT: 500m
SUMO_CPU_REQUEST: 100m

# Rollout settings
SUMO_WEB_MAX_SURGE: 3
SUMO_WEB_MAX_UNAVAILABLE: 0
SUMO_CELERY_MAX_SURGE: 1
SUMO_CELERY_MAX_UNAVAILABLE: 0
SUMO_CRON_MAX_SURGE: 1
SUMO_CRON_MAX_UNAVAILABLE: 1

# Service settings
SUMO_NODEPORT_NAME: sumo-nodeport

# Replicas
SUMO_CELERY_REPLICAS: 1
SUMO_CRON_REPLICAS: 1
SUMO_WEB_REPLICAS: 3


# Readiness probes

# Liveness/readiness probes
SUMO_LIVENESS_FAILURE_THRESHOLD: 1
SUMO_LIVENESS_INITIAL_DELAY_SECONDS: 5
SUMO_LIVENESS_PERIOD_SECONDS: 5
SUMO_LIVENESS_SUCCESS_THRESHOLD: 1
SUMO_LIVENESS_TCP_SOCKET_PORT: 8000
SUMO_LIVENESS_TIMEOUT_SECONDS: 5

SUMO_READINESS_FAILURE_THRESHOLD: 1
SUMO_READINESS_INITIAL_DELAY_SECONDS: 5
SUMO_READINESS_PERIOD_SECONDS: 5
SUMO_READINESS_SUCCESS_THRESHOLD: 1
SUMO_READINESS_TCP_SOCKET_PORT: 8000
SUMO_READINESS_TIMEOUT_SECONDS: 5




# New Relic
SUMO_ENV_NEW_RELIC_APP_NAME: sumo-stage-oregon
