kubernetes:
    app_name: "sumo-stage"
    namespace: "sumo-stage"
    target_environment: "stage"
    nodeport_name: "sumo-nodeport"
    secrets_name: "sumo-secrets-stage"
    image:
        repo: "mozmeao/kitsune"
        tag: "full-latest"
        pull_policy: "Always"
    # default values
    limits:
        memory_limit: 1Gi
        memory_request: 256Mi
        cpu_limit: 500m
        cpu_request: 100m
    replicas: 1
    rollouts:
        max_surge: 1
        max_unavailable: 0
    readiness: False
    liveness: False
    # app specific values
    apps:
        cron:
            command: "./bin/run-cron.sh"
            deployment_name: "sumo-stage-cron"
            replicas: 0
        celery:
            command: "./bin/run-celery-worker.sh"
            deployment_name: "sumo-stage-celery"
            replicas: 0
        web:
            command: "./bin/run-prod.sh"
            deployment_name: "sumo-stage-web"
            replicas: 3
            rollouts:
                max_surge: 3
                max_unavailable: 0
            readiness:
                failure_threshold: 2
                initial_delay_seconds: 20
                period_seconds: 5
                success_threshold: 1
                timeout_seconds: 5
            liveness:
                failure_threshold: 2
                initial_delay_seconds: 20
                period_seconds: 5
                success_threshold: 1
                timeout_seconds: 5

app:
    allowed_cidr_nets: SECRET
    allowed_hosts: ".sumo.moz.works,support.allizom.org"
    aws_access_key_id: SECRET
    aws_s3_custom_domain: SECRET
    aws_secret_access_key: SECRET
    aws_storage_bucket_name: SECRET
    broker_url: SECRET
    cache_url: SECRET
    celery_already_eager: False
    csrf_cookie_secure: True
    database_url: SECRET
    db_conn_max_age: 60
    debug: False
    dms_auto_archive_old_questions: SECRET
    dms_cache_most_unhelpful_kb_articles: SECRET
    dms_calculate_csat_metrics: SECRET
    dms_clear_expired_auth_tokens: SECRET
    dms_cohort_analysis: SECRET
    dms_enqueue_lag_monitor_task: SECRET
    dms_fix_current_revisions: SECRET
    dms_generate_missing_share_links: SECRET
    dms_process_exit_surveys: SECRET
    dms_purge_hashes: SECRET
    dms_rebuild_kb: SECRET
    dms_reindex: SECRET
    dms_reindex_users_that_contributed_yesterday: SECRET
    dms_reload_question_traffic_stats: SECRET
    dms_reload_wiki_traffic_stats: SECRET
    dms_remove_expired_registration_profiles: SECRET
    dms_report_employee_answers: SECRET
    dms_send_weekly_ready_for_review_digest: SECRET
    dms_send_welcome_emails: SECRET
    dms_survey_recent_askers: SECRET
    dms_update_contributor_metrics: SECRET
    dms_update_l10n_contributor_metrics: SECRET
    dms_update_l10n_coverage_metrics: SECRET
    dms_update_l10n_metric: SECRET
    dms_update_product_details: SECRET
    dms_update_top_contributors: SECRET
    dms_update_weekly_votes: SECRET
    k8s_domain: "oregon-a.moz.works"
    email_host: SECRET
    email_host_user: SECRET
    email_host_password: SECRET
    email_port: 25
    email_use_tls: True
    enable_admin: False
    enable_whitenoise: True
    engage_robots: False
    es_index_prefix: "sumo_stage"
    es_http_auth: SECRET
    es_live_indexing: True
    es_use_ssl: True
    es_urls: SECRET
    ga_account: SECRET
    ga_key: SECRET
    ga_profile_id: SECRET
    media_url: "https://stage-cdn.sumo.mozilla.net/"
    new_relic_app_name: "sumo-stage-oregon-a"
    new_relic_license_key: SECRET
    pipeline_enabled: True
    port: 8000
    read_only: True
    redis_default_url: SECRET
    redis_helpfulvotes_url: SECRET
    secret_key: SECRET
    sentry_dsn: SECRET
    session_cookie_secure: True
    stage: False
    static_url: "https://static-media-stage-cdn.sumo.mozilla.net/static/"
    statsd_client: SECRET
    statsd_host: SECRET
    statsd_prefix: "sumo-stage.oregon-a"
    secure_hsts_seconds: 0
    secure_browser_xss_filter: True
    secure_content_type_nosniff: True
    secure_ssl_redirect: True
