kubernetes:
    app_name: "sumo-prod"
    namespace: "sumo-prod"
    target_environment: "prod"
    nodeport_name: "sumo-nodeport"
    secrets_name: "sumo-secrets-prod"
    image:
        repo: "itsre/sumo-kitsune"
        tag: "full-latest"
        pull_policy: "Always"
    # default values
    limits:
        memory_request: 384Mi
        memory_limit: 1Gi
        cpu_request: 250m
        cpu_limit: 1000m
    replicas: 1
    rollouts:
        max_surge: 25%
        max_unavailable: 25%
    readiness: False
    liveness: False
    # app specific values
    apps:
        cron:
            command: "./bin/run-cron.sh"
            deployment_name: "sumo-prod-cron"
            replicas: 0
            labels:
                type: "cron"
        celery:
            command: "./bin/run-celery-worker.sh"
            deployment_name: "sumo-prod-celery"
            replicas: 3
            labels:
                type: "celery"
        web:
            command: "./bin/run-prod.sh"
            deployment_name: "sumo-prod-web"
            replicas: 25
            labels:
                type: "web"
            liveness:
                failure_threshold: 2
                initial_delay_seconds: 5
                period_seconds: 5
                success_threshold: 1
                timeout_seconds: 5

app:
    allowed_cidr_nets: SECRET
    allowed_hosts: ".sumo.mozit.cloud,support.mozilla.com,support.mozilla.org"
    aws_access_key_id: SECRET
    aws_s3_custom_domain: SECRET
    aws_secret_access_key: SECRET
    aws_storage_bucket_name: SECRET
    broker_url: SECRET
    cache_middleware_seconds: 0
    cache_url: SECRET
    celery_already_eager: False
    csrf_cookie_secure: True
    database_url: SECRET
    db_conn_max_age: 60
    debug: False
    dms_auto_archive_old_questions: SECRET
    dms_cache_most_unhelpful_kb_articles: SECRET
    dms_calculate_csat_metrics: SECRET
    dms_cohort_analysis: SECRET
    dms_enqueue_lag_monitor_task: SECRET
    dms_fix_current_revisions: SECRET
    dms_generate_missing_share_links: SECRET
    dms_process_exit_surveys: SECRET
    dms_rebuild_kb: SECRET
    dms_reindex: SECRET
    dms_reindex_users_that_contributed_yesterday: SECRET
    dms_reload_question_traffic_stats: SECRET
    dms_reload_wiki_traffic_stats: SECRET
    dms_report_employee_answers: SECRET
    dms_send_weekly_ready_for_review_digest: SECRET
    dms_send_welcome_emails: SECRET
    dms_survey_recent_askers: SECRET
    dms_update_contributor_metrics: SECRET
    dms_update_l10n_contributor_metrics: SECRET
    dms_update_l10n_coverage_metrics: SECRET
    dms_update_l10n_metric: SECRET
    dms_update_product_details: SECRET
    dms_update_top_contributors: SECRET
    dms_update_weekly_votes: SECRET
    k8s_domain: "oregon-b.mozit.cloud"
    email_host: SECRET
    email_host_user: SECRET
    email_host_password: SECRET
    email_logging_real_backend: "django.core.mail.backends.smtp.EmailBackend"
    email_port: 25
    email_use_tls: True
    enable_admin: True
    enable_whitenoise: True
    enforce_host: "support.mozilla.org,prod-oregon-b.sumo.mozit.cloud,prod-tp.sumo.mozit.cloud"
    engage_robots: True
    es_index_prefix: "sumo_prod"
    es_http_auth: SECRET
    es_live_indexing: True
    es_use_ssl: True
    es_urls: SECRET
    ga_account: SECRET
    ga_key: SECRET
    ga_profile_id: SECRET
    gtm_container_id: "UA-36116321-2"
    media_url: "https://user-media-prod-cdn.itsre-sumo.mozilla.net/"
    new_relic_app_name: "sumo-prod-oregon-b;sumo-prod-oregon"
    new_relic_license_key: SECRET
    oidc_enable: True
    oidc_op_authorization_endpoint: SECRET
    oidc_op_token_endpoint: SECRET
    oidc_op_user_endpoint: SECRET
    oidc_rp_client_id: SECRET
    oidc_rp_client_secret: SECRET
    pipeline_enabled: True
    port: 8000
    read_only: False
    redis_default_url: SECRET
    redis_helpfulvotes_url: SECRET
    secret_key: SECRET
    session_cookie_secure: True
    stage: False
    static_url: "https://static-media-prod-cdn.itsre-sumo.mozilla.net/static/"
    statsd_client: SECRET
    statsd_host: SECRET
    statsd_prefix: "sumo-prod.oregon-b"
    secure_hsts_seconds: 31536000
    secure_browser_xss_filter: True
    secure_content_type_nosniff: True
    secure_ssl_redirect: True
    surveygizmo_user: SECRET
    surveygizmo_password: SECRET
    surveygizmo_api_token: SECRET
    surveygizmo_api_token_secret: SECRET
    user_agent_filters: "360spider,semrushbot,coccobot,dotbot"
    wsgi_keep_alive: 60
    wsgi_num_workers: 4
    disable_questions_list_global: False
    disable_questions_list_all: False
    disable_feeds: False
    sentry_dsn: SECRET
    fxa_op_token_endpoint: SECRET
    fxa_op_authorization_endpoint: SECRET
    fxa_op_user_endpoint: SECRET
    fxa_op_subscription_endpoint: SECRET
    fxa_op_jwks_endpoint: SECRET
    fxa_rp_client_id: SECRET
    fxa_rp_client_secret: SECRET
    sumo_banner_string: "firefox-account,firefox-monitor,account-data,firefox-private-network"
