
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: sumo-{{ TARGET_ENVIRONMENT }}
    type: env
  name: {{ SUMO_SECRETS_NAME }}
  namespace: sumo-{{ TARGET_ENVIRONMENT }}
type: Opaque
data:
  aws-access-key-id:
  aws-s3-custom-domain:
  aws-secret-access-key:
  aws-storage-bucket-name:
  broker-url:
  cache-url:
  database-read-only-url:
  database-url:
  es-http-auth:
  es-urls:
  redis-default-url:
  redis-helpfulvotes-url:
  secret-key:
  dms-auto-archive-old-questions:
  dms-cache-most-unhelpful-kb-articles:
  dms-calculate-csat-metrics:
  dms-clear-expired-auth-tokens:
  dms-cohort-analysis:
  dms-enqueue-lag-monitor-task:
  dms-fix-current-revisions:
  dms-generate-missing-share-links:
  dms-process-exit-surveys:
  dms-purge-hashes:
  dms-rebuild-kb:
  dms-reindex-kb:
  dms-reindex-users-that-contributed-yesterday:
  dms-reload-question-traffic-stats:
  dms-reload-wiki-traffic-stats:
  dms-remove-expired-registration-profiles:
  dms-report-employee-answers:
  dms-send-weekly-ready-for-review-digest:
  dms-send-welcome-emails:
  dms-survey-recent-askers:
  dms-update-contributor-metrics:
  dms-update-l10n-contributor-metrics:
  dms-update-l10n-coverage-metrics:
  dms-update-l10n-metric:
  dms-update-product-details:
  dms-update-top-contributors:
  dms-update-weekly-votes:
  ga-account:
  ga-key:
  ga-profile-id:
  statsd-client:
  statsd-host:
  statsd-prefix:
