name: Publish Docs in GitHub Pages

on:
  workflow_dispatch: # allow manual runs
  push:
    branches:
      - main
    paths: # avoid building unless needed
      - docs/**
      - mkdocs.yml
      - kitsune/sumo/static/sumo/scss/**
      - styleguide/**
      - .github/workflows/publish-docs.yml

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false # skip any intermediate builds but let finish

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
          cache: pip
      - id: pages
        uses: actions/configure-pages@v5
      - name: Build docs
        run: |
          pip install mkdocs-material
          mkdocs build -d site
      - name: Build styleguide
        run: |
          npm ci
          npm run build:styleguide
          mkdir site/_kss
          cp -r styleguide/build/. site/_kss/
      - uses: actions/upload-pages-artifact@v4
        with:
          path: site
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
